<a href="https://colab.research.google.com/github/harishpaasu/wallet-1/blob/main/ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#Create a 0-D array with the value 25 and print it.

import numpy as np
arr0=np.array(25)
print(arr0)

25


In [11]:
#Create a 1-D array containing numbers from 1 to 10.
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)


[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
#Create a 2-D array with two rows: [1, 2, 3] and [4, 5, 6].
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)


[[1 2 3]
 [4 5 6]]


In [16]:
#Create a 3-D array that contains two 2-D matrices of size 2×2 each
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
#Print the number of dimensions (ndim) of each of the above arrays.
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3.ndim)

3


In [19]:
#Convert the Python list [10, 20, 30, 40] into a NumPy array and print it.
import numpy as np
arr1=np.array([10,20,30,40])
print(arr1)

[10 20 30 40]


In [20]:
#Create a 1-D array with even numbers between 2 and 20.
import numpy as np
arr2=np.array([2,4,6,8,10,12,14,16,18,20])
print(arr2)

[ 2  4  6  8 10 12 14 16 18 20]
